# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solve_infections <- function(beta, gamma, t_1, initial_impulse, N) {
    .Call(`_smesir_solve_infections`, beta, gamma, t_1, initial_impulse, N)
}

solve_events <- function(nu, psi) {
    .Call(`_smesir_solve_events`, nu, psi)
}

log_poisd <- function(y, lambda) {
    .Call(`_smesir_log_poisd`, y, lambda)
}

log_llh <- function(B, Y, gamma, T_1, Initial_Impulse, N, psi) {
    .Call(`_smesir_log_llh`, B, Y, gamma, T_1, Initial_Impulse, N, psi)
}

log_llh2 <- function(B, Y, gamma, T_1, Initial_Impulse, N, psi, C0i) {
    .Call(`_smesir_log_llh2`, B, Y, gamma, T_1, Initial_Impulse, N, psi, C0i)
}

smesir_mcmc <- function(Y, Design_Matrices, lambda, V0param, IGSR, gamma, T_1, Initial_Impulse, N, psi, tempering_ratio, ncycles, samps_per_cycle, nchain, iter, warmup, thin, sr_style, quiet) {
    .Call(`_smesir_smesir_mcmc`, Y, Design_Matrices, lambda, V0param, IGSR, gamma, T_1, Initial_Impulse, N, psi, tempering_ratio, ncycles, samps_per_cycle, nchain, iter, warmup, thin, sr_style, quiet)
}

